# Generated by Django 2.0.7 on 2018-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupSession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_number', models.IntegerField()),
            ],
        ),
    ]
