# Generated by Django 2.0.7 on 2018-08-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixachat_number', models.IntegerField()),
                ('croix_number', models.IntegerField()),
                ('quantity_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Type'),
        ),
    ]
