# Generated by Django 2.0.7 on 2018-08-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaty_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cross',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
