# Generated by Django 2.0.7 on 2018-08-31 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eaty_product', '0002_auto_20180830_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eaty_product.ProductType'),
        ),
    ]
